b1=open("f1.txt","r+")
str1=(b1.read(15))
print("string is :",str1)
pos=b1.tell()
print("present possition of file is : ",pos)
pos=b1.seek(20)
print(pos)
str2=b1.read(15)
print("recheked string is: ",str2)
